### ISSUE TITLE
 Building back from decompilation to apk fails

### ISSUE THREAD

**Issue by sekaiacg** [REAndroid/APKEditor#20]
**1.APKEditor version:** 1.2.0
**2.apk file:** [Settings.apk](https://drive.google.com/file/d/1E7aZ0Kn1I5Ee5fvitdVQQ6oyBrLBLWIT/view?usp=sharing)

**3.run: java -jar APKEditor.jar d -i Settings.apk**
```
00.000 I: [DECOMPILE] Decompiling ...
   Input: Settings.apk
 Output: Settings_decompile_null
 Type: json
 Split: false
 ---------------------------- 
00.020 I: [DECOMPILE] Loading ...
00.579 I: [DECOMPILE] Initializing android framework ...
00.579 I: [DECOMPILE] Loading android framework for version: 33
00.614 I: [DECOMPILE] Initialized framework: android-33
00.614 I: [DECOMPILE] Decompiling to JSON ...
00.659 I: [DECOMPILE] [SANITIZE]: Sanitizing paths ...
00.663 [DECOMPILE] [SANITIZE]: REN: 'META-INF/external__kotlinx.coroutines__android_common__kotlinx_cor                                                                                                       00.663 [DECOMPILE] [SANITIZE]: REN: 'META-INF/packages__apps__MiuiSettingsLib__android_common__MiuiSettingsLib.kotlin_module' -> 'META-INF/alias_45341996'
00.667 I: [DECOMPILE] [SANITIZE]: DONE = 10572
03.648 I: [DECOMPILE] Dumping signatures ...
03.648 I: [DECOMPILE] Saved to: Settings_decompile_null
03.648 I: [DECOMPILE] Done
```

**do not make any changes.**

**4.run: java -jar APKEditor.jar b -i Settings_decompile_null**
```
00.000 I: [BUILD] Building ...
   Input: Settings_decompile_null/base
 Output: Settings_decompile_null_out.apk
 ---------------------------- 
00.019 I: [BUILD] Scanning JSON directory ...
00.103 I: [BUILD] Restoring file path ...
00.104 I: [BUILD] Building resources table: resources.arsc

Unexpected error:
java.io.IOException: resources.arsc: JSONObject["style"] not found.
java.lang.IllegalArgumentException: java.io.IOException: resources.arsc: JSONObject["style"] not found.
	at com.reandroid.apk.ApkModule.getTableBlock(ApkModule.java:566)
	at com.reandroid.apk.ApkModule.getTableBlock(ApkModule.java:573)
	at com.reandroid.apk.ApkModule.listResFiles(ApkModule.java:398)
	at com.reandroid.apk.ApkModule.listResFiles(ApkModule.java:394)
	at com.reandroid.apk.PathMap.restore(PathMap.java:37)
	at com.reandroid.apk.ApkJsonEncoder.restorePathMap(ApkJsonEncoder.java:82)
	at com.reandroid.apk.ApkJsonEncoder.scanDirectory(ApkJsonEncoder.java:48)
	at com.reandroid.apkeditor.compile.Builder.buildJson(Builder.java:69)
	at com.reandroid.apkeditor.compile.Builder.run(Builder.java:49)
	at com.reandroid.apkeditor.compile.Builder.execute(Builder.java:159)
	at com.reandroid.apkeditor.Main.execute(Main.java:65)
	at com.reandroid.apkeditor.Main.main(Main.java:38)
Caused by: java.io.IOException: resources.arsc: JSONObject["style"] not found.
	at com.reandroid.apk.SingleJsonTableInputSource.getTableBlock(SingleJsonTableInputSource.java:68)
	at com.reandroid.apk.ApkModule.loadTableBlock(ApkModule.java:652)
	at com.reandroid.apk.ApkModule.getTableBlock(ApkModule.java:560)
	... 11 more
```

**Comment by sekaiacg** [comment]
**Thanks ！no more json errors, this problem has been perfectly fixed.** 
I tried -t xml but it causes incorrect ui layout. Using other tools to view the compiled resources.arsc file prompts an error. Maybe some apk in this rom is obfuscated, everything works fine with json.

UI problem after using xml:
![QQ_Image_1683026700983](https://user-images.githubusercontent.com/33929605/235653407-069d2461-7371-43f5-830a-8e41b10e0547.jpg)


error info:
![QQ_Image_1683026293247](https://user-images.githubusercontent.com/33929605/235652481-f9abb15e-0347-4025-a9ac-b1ca93ec7e68.jpg)

```
TAG: 2.13.4(23040183)
ROOT: true
ABI: arm64-v8a
MODEL: 22021211RC
SDK: 33
RELEASE: 13
---StackTrace---
java.lang.RuntimeException:  [com.android](http://com.android/) .settings/attr/actionBarSplitMaxPercentageHeight 192 65472
	at l.ۧ۟ۛ.ۨ(L63Q:152)
	at l.۠۟ۛ.ۨ(05W2:138)
	at l.ۖ۟ۛ.ۨ(15Y4:149)
	at l.۟۟ۛ.ۨ(D622:174)
	at l.ۢ۟ۛ.ۨ(W54R:118)
	at l.ۛ۟ۛ.ۨ(S4NY:62)
	at l.ۗۡۧ.ۨ(21FW:1008)
	at l.ۗۡۧ.ۖ(21FW:835)
	at l.ۗ۟ۧ.ۥ(81KA:569)
	at l.ۨۙۨۨ.ۨ(U4WR:101)
	at l.ۤۤ۟.run(DATL:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker( [ThreadPoolExecutor.java:1137](http://threadpoolexecutor.java:1137/) )
	at java.util.concurrent.ThreadPoolExecutor$Worker.run( [ThreadPoolExecutor.java:637](http://threadpoolexecutor.java:637/) )
	at  [java.lang.Thread.run](http://java.lang.thread.run/) ( [Thread.java:1012](http://thread.java:1012/) )
```

**Comment by sekaiacg** [comment]
thanks for your work.

**Comment by sekaiacg** [comment]
**I conducted a test, resources.arsc is no longer wrong.**
but the UI layout is not correct, is there a problem with xml parsing?
I used the recompiled apk (xml) to decompile to json format again, and found that it could not match the original apk decompiled json file in some places.

The left side uses the xml format and decompiles it into json again.(Settings_decompile_xml_out_decompile_json)
example:
base/res-json/res/drawable-sw600dp-v13/core_scan_gesture_broadside.xml.json
![1](https://user-images.githubusercontent.com/33929605/235833286-fa5bfb95-9ff7-4d70-a594-bd2ccb630b99.png)
![2](https://user-images.githubusercontent.com/33929605/235833304-088f33d1-e6b5-4dd2-9e4f-079a1827243c.png)

**Comment by sekaiacg** [comment]
> The error was DIMESION value encode/decode. On this case raw value -47615 supposed to be decoded as -186.0dp. Now this issue seems to be fixed and check the latest update.
> 
> You are pointing out good issues, hope you will keep doing same. Thank You !

**After testing, the UI layout is normal.**
Another question:
value_type:
Do INT_COLOR_ARGB8(xml) and INT_COLOR_RGB8(json) represent the same type?
The results of xml and json are inconsistent.

**Comment by sekaiacg** [comment]
**Question 1:**
I found that some resource hooks in the apk compiled back using xml are invalid (third-party themes can change the text options in the settings, but some do not take effect).
![QQ_Image_1683124917618](https://user-images.githubusercontent.com/33929605/235950735-654600b7-4fae-4fe4-baa1-d5ec5580a001.jpg)

```
If it does not take effect, the default content will be used:
        "entry_name": "personalize_title",
        "value": {
         "value_type": "STRING",
         "data": "壁纸与个性化"
        },
```

The strange thing is that the problem disappears after decompiling the problematic apk using json and then compiling it back to apk.
Settings_decompile_xml_out.apk : **not take effect**
Settings_decompile_xml_out_decompile_json_out.apk : **take effect**

I think compiling back to apk with xml might cause some unknown issues.

------
**Question 2:**
When decompiling AndroidManifest.xml, extra spaces and characters appear: '
![3](https://user-images.githubusercontent.com/33929605/235953067-33e3a977-240d-4cf7-b88d-ac9c2c84b490.png)

**Comment by REAndroid** [comment]
> **Question 1:** I found that some resource hooks in the apk compiled back using xml are invalid (third-party themes can change the text options in the settings, but some do not take effect). 

On your apk, the value was decoded as 
```<string name="personalize_title">Wallpaper &amp;amp; personalization</string>``` for value of
 ```Wallpaper & personalization``` . But I am not sure it will fix this issue, I will get back after making some investigation, in the meantime check the latest update

**Comment by sekaiacg** [comment]
> > Another question: value_type: INT_COLOR_ARGB8(xml) and INT_COLOR_RGB8(json) represent the same type? The results of xml and json are inconsistent.
> 
> This was wrong, now fixed
> 
> > Question 2:
> > When decompiling AndroidManifest.xml, extra spaces and characters appear: '
> 
> This is correct parsing, those additional characters are existed on original bin xml

I use the latest updated version for testing:
1.INT_COLOR_RGB8 fixed.
2.Question 1 still exists

**Comment by sekaiacg** [comment]
> > Another question: value_type: INT_COLOR_ARGB8(xml) and INT_COLOR_RGB8(json) represent the same type? The results of xml and json are inconsistent.
> 
> This was wrong, now fixed
> 
> > Question 2:
> > When decompiling AndroidManifest.xml, extra spaces and characters appear: '
> 
> This is correct parsing, those additional characters are existed on original bin xml

1.INT_COLOR_RGB8 fixed.

**Comment by REAndroid** [comment]
>  2.Question 1 still exists. 3.Because there are special characters in the original AndroidManifest.xml, it can also be expected.

The developer of this apk put those characters AndroidManifest.xml for some reason or mistake. Not the problem of the parser. Check ```AndroidManifest.xml.json``` 

```json
      {
       "node_type": "text",
       "text": " ' "
      }
```

**Comment by sekaiacg** [comment]
> 

ok, I know, thank you.

**Comment by sekaiacg** [comment]
Hi, the problem caused by using xml was also found in other apk.

In the following apk, after compiling back with xml, the options in the red box are not displayed.
apk file: [Home_test.zip](https://drive.google.com/file/d/1HzKysb6JtqlXsnhSAhVRVUdbMLacoxM5/view?usp=share_link)
![IMG_20230504_201701](https://user-images.githubusercontent.com/33929605/236203331-1aeb59a8-6ca6-4b9d-8c01-fe586de480dd.png)

At the same time, some devices may crash after installing the apk.
```
05-04 20:28:37.629 15524 15524 E AndroidRuntime: FATAL EXCEPTION: main
05-04 20:28:37.629 15524 15524 E AndroidRuntime: Process: com.miui.home, PID: 15524
05-04 20:28:37.629 15524 15524 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
05-04 20:28:37.629 15524 15524 E AndroidRuntime: 	at miuix.preference.DropDownPreference$1$1.run(DropDownPreference.java:67)
05-04 20:28:37.629 15524 15524 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
05-04 20:28:37.629 15524 15524 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-04 20:28:37.629 15524 15524 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
05-04 20:28:37.629 15524 15524 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
05-04 20:28:37.629 15524 15524 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8116)
05-04 20:28:37.629 15524 15524 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-04 20:28:37.629 15524 15524 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
05-04 20:28:37.629 15524 15524 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
There is no problem parsing with json, all works fine.

**Comment by REAndroid** [comment]
Odd apk , arrays supposed to have attributes ```0x01000000```, ```0x01000001```, ```0x01000002``` ... but this apk has all name values 0. My guess is that it was modified by non aapt tool.

Anyways it's fixed now check the latest updates

**Comment by sekaiacg** [comment]
> Odd apk , arrays supposed to have attributes `0x01000000`, `0x01000001`, `0x01000002` ... but this apk has all name values 0. My guess is that it was modified by non aapt tool.
> 
> Anyways it's fixed now check the latest updates

I used the latest updated version to test, and the problem still persists.
Is there a better way to find the problem?

**Comment by REAndroid** [comment]
> Why is json parsing correct and xml wrong? Are their implementations different?

Good question, Consider dex(dalvik)  decompiling we can decompile/compile to ```smali``` or ```java``` but most of the times java gets error

- converting ```ARSC``` to/from ```XML``` is like converting ```DEX``` to/from ```JAVA``` 
- converting ```ARSC``` to/from ```JSON``` is like converting ```DEX``` to/from ```SMALI``` 

Decompiling to XML is not 1:1 it is based on guess and assumptions e.g. you have a value ```1234``` there is no direct way to tell for XML this is ```STRING``` or ```INTEGER``` or ```FLOAT``` but for JSON you simply specify it with ```value_type:"xxxx"```. XML by itself has its own limitation/weakness. 

This is the reason why i came up with idea of **JSON** format as an agent between low level byte code and humans to modify binary resources with 100% accuracy. If you check commits history I added XML support lately because most developers are used to **XML** and got confused with the new **JSON**. 

I always recommend to use JSON format (if you are good at it) it is guaranteed to be 100% accurate. 

Anyways we will keep improving XML conversion but there is no logical way to reach 100% error free.

**Comment by REAndroid** [comment]
> smallwindow_icon.xml.json:
> <img src="https://user-images.githubusercontent.com/33929605/236364528-9085a346-869c-42a4-845a-0513ac1fedf8.png" height="150"/>

Fixed with this [commit](https://github.com/REAndroid/ARSCLib/commit/58f75481c273e09ce09a32e1af832b7d8d180cc4) I will update releases latter after fixing other issues

**Comment by sekaiacg** [comment]
Thanks for your answer, I understand the difference between xml and json. I will test it after fixing the problem.

**Comment by REAndroid** [comment]
Fixed major issues and release updated, you can test it now

**Comment by sekaiacg** [comment]
> Fixed major issues and release updated, you can test it now

I tested with the latest update:
1. The STRING type of resources.arsc.json has been fixed
2. The data of DIMENSION and INT_COLOR_RGB4 has been fixed
Now the apk basically works fine.

**Comment by sekaiacg** [comment]
At the same time, compared with the previous APK, it is found that some xml has special characters, but after parsing the xml for the second time, there are more newlines and spaces after the special characters, which is different from the previous format. Probably similar to the json in the previous question.
apk file: [Settings_test3.zip](https://drive.google.com/file/d/1fWNb6z9EZzHMR_q61wnliN3WMjRSFMAe/view?usp=share_link)
**The right is parsed directly through XML.**
Settings_decompile_xml_out_decompile_xml---------------------------------Settings_decompile_xml
res/drawable/color_bar_progress.xml:
![1](https://user-images.githubusercontent.com/33929605/236590678-a24081cc-d200-4cbc-b6da-2033ae22545c.png)

**Through simple comparison, it is found that the content in some xml is different or missing:**
res/values/colors.xml:
![2](https://user-images.githubusercontent.com/33929605/236590830-0b0f3f55-695b-40ad-923e-eb4484a3223b.png)

res/values/dimens.xml:
![3](https://user-images.githubusercontent.com/33929605/236590862-fedb1292-85b6-4b9a-8547-cc6f941c7487.png)

res/values/strings.xml:
![4](https://user-images.githubusercontent.com/33929605/236590905-a2b4e1b4-f50d-4061-9646-2c1d4e468285.png)

**The right side is parsed directly using json.**
Settings_decompile_xml_out_decompile_json----------------------------------------Settings_decompile_json
res/layout/accessibility_edit_shortcut_magnification_pad.xml.json:
value_type inconsistent
![5](https://user-images.githubusercontent.com/33929605/236591442-96b3d592-c3d5-4f51-8ca8-b48c30eccb0c.png)

**Comment by REAndroid** [comment]
- Color
- Style string

Seems to be fixed now, check updates

**Comment by sekaiacg** [comment]
> * Color
> * Style string
> 
> Seems to be fixed now, check updates

1.Color has been fixed.
2. There is still a problem with the string, the content lacks spaces, I am very sorry, I ignored it yesterday.
res/values/strings.xml:
![6](https://user-images.githubusercontent.com/33929605/236657719-8746bc99-588a-4e9c-bdb0-a2098f57d809.png)
3. Other problems are still not fixed(value_type...).

**Comment by sekaiacg** [comment]
> **Question 1:** I found that some resource hooks in the apk compiled back using xml are invalid (third-party themes can change the text options in the settings, but some do not take effect). ![QQ_Image_1683124917618](https://user-images.githubusercontent.com/33929605/235950735-654600b7-4fae-4fe4-baa1-d5ec5580a001.jpg)
> 
> ```
> If it does not take effect, the default content will be used:
>         "entry_name": "personalize_title",
>         "value": {
>          "value_type": "STRING",
>          "data": "壁纸与个性化"
>         },
> ```
> 
> The strange thing is that the problem disappears after decompiling the problematic apk using json and then compiling it back to apk. Settings_decompile_xml_out.apk : **not take effect** Settings_decompile_xml_out_decompile_json_out.apk : **take effect** apk file: [Settings_test2.zip](https://drive.google.com/file/d/1eIWlpdTM_e5kp2JmYeYlWeWgJtdDiiVi/view?usp=share_link)
> 
> I think compiling back to apk with xml might cause some unknown issues.
> 
> **Question 2:** When decompiling AndroidManifest.xml, extra spaces and characters appear: ' ![3](https://user-images.githubusercontent.com/33929605/235953067-33e3a977-240d-4cf7-b88d-ac9c2c84b490.png)

----
**I'm using the latest updated version and haven't modified anything, so I don't understand what the difference is. This is a very miraculous phenomenon.**

apk→xml→apk: **not take effect**
apk→xml→apk→json→apk: **take effect**

Add 2 content that has no effect:
```
        "entry_name": "display_settings",
        "value": {
         "value_type": "STRING",
         "data": "Display"
        },
...
        "entry_name": "sound_haptic_settings",
        "value": {
         "value_type": "STRING",
         "data": "Sound & touch"
        },
```

I'm using the latest updated version and haven't modified anything, so I don't understand what the difference is. This is a very miraculous phenomenon.

**Comment by REAndroid** [comment]
- DIMENSION: 
   1) When you divide/multiply integers to float you will loose fractional values , e.g if you _encode-decode-encode_ value ```1.0dp``` without any adjustment the result will be 0.999999dp, that is why I tried to round up digits with best result possible.
   2) Encoding dimension to integer is a bit complicated  check AOSP [Line 379-386](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/libs/androidfw/include/androidfw/ResourceTypes.h;l=379-386) e.g value ```180.0dp``` can be encoded to integer ```46081``` or ```5898257``` if you decode this values the result is the same. So you might see different integer result on JSON but it is the same.

- STRING:
   1) >  2 . There is still a problem with the string, the content lacks spaces

      Yes I confirm, it will be fixed

I will fix this and other issues and get back to you

**Comment by REAndroid** [comment]
>Question 1: I found that some resource hooks in the apk compiled back using xml are invalid (third-party themes can change the text options in the settings, but some do not take effect). 

I can't figure out where exactly this problem is. I compared (using custom program byte level) files built with json & xml, most differences are irrelevant except config size 64(xml) & 48(json) and I doubt this fixes your issue.

I updated releases, you can test now and it will be better if you can get some stacktraces/logs

**Comment by sekaiacg** [comment]
I tested with the latest updated version.
The latest version causes the APK language resource to be abnormal. It is set to Simplified Chinese, but it is actually Traditional Chinese, and the language cannot be switched...
The results after 2 decompilations using xml cannot be compared...
Settings_decompile_xml_out_decompile_xml--------------------------------Settings_decompile_xml
![01](https://github.com/REAndroid/APKEditor/assets/33929605/db9ac500-ffd4-4479-a9b6-baf5f8f11b96)

I think the new version may have broken some resources

**Comment by REAndroid** [comment]
Ohh I made silly mistake [here](https://github.com/REAndroid/ARSCLib/commit/427e12194fab6dd18341a9926d5aa316c6ab9f2c).
Check the latest update

**Comment by REAndroid** [comment]
Can you send me some of "third-party" apps ?

**Comment by sekaiacg** [comment]
> Can you send me some of "third-party" apps ?

The theme will not generate effects on third-party apps.

This is the theme supported by MIUI ROM. It requires the built-in ThemeManager.apk to apply. It can modify option text in settings (Settings.apk).
Using -t xml to compile APK (Settings.apk) will cause some options to be unable to be modified.

**Comment by REAndroid** [comment]
No point closing this issue without finding out the exact problem. I am making new separate program to compare resources in detail. I will get back to you when it is done

**Comment by REAndroid** [comment]
Here I made a massive change you can test it with [APKEditor-1.2.0-UPDATE-01.jar](https://github.com/REAndroid/APKEditor/releases/download/V1.2.0/APKEditor-1.2.0-UPDATE-01.jar)

- The only problem I found was it doesn't remove unused  strings from pool

**Comment by sekaiacg** [comment]
> Here I made a massive change you can test it with [APKEditor-1.2.0-UPDATE-01.jar](https://github.com/REAndroid/APKEditor/releases/download/V1.2.0/APKEditor-1.2.0-UPDATE-01.jar)
> 
> * The only problem I found was it doesn't remove unused  strings from pool

This version does not solve the problem.
This question is very peculiar....

**Comment by REAndroid** [comment]
Check  [APKEditor-1.2.0-UPDATE-02.jar](https://github.com/REAndroid/APKEditor/releases/download/V1.2.0/APKEditor-1.2.0-UPDATE-01.jar)

**Comment by REAndroid** [comment]
> Settings_decompile_xml_out.apk: not take effect
> Settings_decompile_xml_out_other_tool_mod.apk: take effect

This files are wrongly edited by your tool and the resource ids are distorted.


Since your apk is also framework, resources must be publicized to be accessible  by other apps.  
Here is an update with other major issues fixed: [APKEditor-1.2.0-UPDATE-03.jar](https://github.com/REAndroid/APKEditor/releases/download/V1.2.0/APKEditor-1.2.0-UPDATE-03.jar)

**Comment by sekaiacg** [comment]
> > Settings_decompile_xml_out.apk: not take effect
> > Settings_decompile_xml_out_other_tool_mod.apk: take effect
> 
> This files are wrongly edited by your tool and the resource ids are distorted.

I don't know what's wrong with this. But this tool recompiles the ARSC file, just modifying it with it will solve the problem. This has the same effect as recompiling with json.
After these tests, it is also proved that the ARSC file compiled by json (APKEditor) is correct.

> Since your apk is also framework, resources must be publicized to be accessible by other apps. Here is an update with other major issues fixed: [APKEditor-1.2.0-UPDATE-03.jar](https://github.com/REAndroid/APKEditor/releases/download/V1.2.0/APKEditor-1.2.0-UPDATE-03.jar)

After testing, this version does not solve the problem.
Below is the original APK/JSON and XML compiled effect. There should be some errors in the ARSC file compiled by xml.
![03](https://github.com/REAndroid/APKEditor/assets/33929605/e3702eb5-f1aa-4e7b-a3fd-3af82ea3f9ca)
![04](https://github.com/REAndroid/APKEditor/assets/33929605/e5f7a628-54b1-43d3-8997-9be78d209ce6)

**Comment by REAndroid** [comment]
- Sorry  I don't know chinese and your screenshots are not helping me at all. If you place it here in raw strings I might be able to copy and do string search it.
 _for example:_ 

 | Correct-Text        | Wrong-Text           |
 | ------------- |:-------------:|
 |无无无无     | 寸寸寸寸寸 |
 |uuuuuu     | vvvvvvvvvv |
 |wwwww     | xxxxxxxxx |

- Is this problem happening on chinese (zh-rCN) language only ? If not please change it to english for better communication.

- Here is my builds based on your original file, now tell me which one is working and which is not (_sign it if required_)

1. ```original``` > ```decompile to xml``` > ```compile```  [Settings_decompile_xml_out.apk](https://mega.nz/file/V95WTAgC#gadC__ANobXYZdBIH8_Nu06Jzg_cJfDFk3kg0nhieyw)
2. ```apk from 1``` > ```decompile to json``` > ```compile```  [Settings_decompile_xml_out_decompile_json_out.apk](https://mega.nz/file/15J2UJZB#py3Lz6V2fEG6iXvafNUKAdB0Ur77i98vYRIuhMzZ1AE)

- Is there a way for me to install and test it on emulator under linux ?

**Comment by sekaiacg** [comment]
I changed the text to English.

- The table below is the test results.The text is modified via a third party theme (without modifying the apk).

| original apk/json(APK Default Text) | json(custom theme: Correct-Text) | xml(custom theme: Wrong-Text) |
|----------------|-------------------|---------|
|Wallpaper &amp; personalization|Wallpaper &amp; personalization test1|Wallpaper &amp; personalization|
|Display|Display test2|Display|
----
![01](https://github.com/REAndroid/APKEditor/assets/33929605/d9b250fc-bd9f-42a4-9ff0-807fe9fcbbb1)
![02](https://github.com/REAndroid/APKEditor/assets/33929605/0bdd8896-0420-4096-96a2-a50ee74392aa)
![03](https://github.com/REAndroid/APKEditor/assets/33929605/47c4ec69-c0ff-48f9-991a-38519d7a12b4)

- The working apk is: **Settings_decompile_xml_out_decompile_json_out.apk**

----
- Very sorry, this apk can't run in other ROM.

**Comment by REAndroid** [comment]
I think I misunderstood you this whole time, when you mean by "**apply-theme**" do you mean edit the apk with other tool ?

**Comment by sekaiacg** [comment]
1. Theme is a feature in ROM which can change the text without modifying the system APK.
2. Settings.apk is the system APK.
3. Settings.apk only use APKEditor to decompile and then compile back. No resources were modified.
Use -t xml to decompile and then compile it back, there will be some text that cannot be covered by the theme.
There will be no problem with json.

This reply explains the phenomenon of the problem in detail:
https://github.com/REAndroid/APKEditor/issues/20#issuecomment-1555944377

Theme Manager: 
![04](https://github.com/REAndroid/APKEditor/assets/33929605/25e2d112-99ec-4ec2-8488-fb3a87a0aff1)

**Comment by REAndroid** [comment]
I found issue on duplicate resource names, check this update [APKEditor-1.2.0-UPDATE-04.jar](https://github.com/REAndroid/APKEditor/releases/download/V1.2.0/APKEditor-1.2.0-UPDATE-04.jar)

**Comment by sekaiacg** [comment]
> I found issue on duplicate resource names, check this update [APKEditor-1.2.0-UPDATE-04.jar](https://github.com/REAndroid/APKEditor/releases/download/V1.2.0/APKEditor-1.2.0-UPDATE-04.jar)

**Great, this version fixes the problem.**

**Comment by sekaiacg** [comment]
Thanks for your work.

**Comment by REAndroid** [comment]
Good ! We have solved a lot of issue on the way. I will update repos with proper release and I will credit you for your contribution. 
Thank you!

**Comment by REAndroid** [comment]
Check the latest release : [V1.2.1](https://github.com/REAndroid/APKEditor/releases/tag/V1.2.1)

**Comment by sekaiacg** [comment]
> Check the latest release : [V1.2.1](https://github.com/REAndroid/APKEditor/releases/tag/V1.2.1)

**After testing, both xml and json are working fine.**
